In [1]:
import tensorflow as tf
import numpy as np

In [2]:
np.random.rand(2,3,4)

array([[[ 0.46536652,  0.1165438 ,  0.98693059,  0.79871224],
        [ 0.65280645,  0.94166748,  0.67146306,  0.67077273],
        [ 0.30557007,  0.22010413,  0.79170203,  0.95931051]],

       [[ 0.55334763,  0.81374374,  0.73352271,  0.17653765],
        [ 0.29755049,  0.60771774,  0.70264042,  0.94040975],
        [ 0.23473885,  0.84891302,  0.91524429,  0.00734637]]])

In [3]:
data = tf.constant(np.random.rand(2,3,4).astype(np.float32), name='ok')

In [4]:
data.dtype

tf.float32

In [5]:
data.name

'ok:0'

In [6]:
data.value_index

0

In [7]:
data.graph

In [8]:
data.op

In [9]:
data.consumers

<bound method Tensor.consumers of <tf.Tensor 'ok:0' shape=(2, 3, 4) dtype=float32>>

In [10]:
data.consumers()

[]

In [11]:
data.eval

<bound method Tensor.eval of <tf.Tensor 'ok:0' shape=(2, 3, 4) dtype=float32>>

In [12]:
c = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
d = tf.constant([[1.0, 0.0], [0.0, 1.0], [1.0, 0.0], [0.0, 1.0]])
e = tf.matmul(c, d, transpose_a=True, transpose_b=True)
print(c.get_shape())
print(d.get_shape())
print(e.get_shape())

(2, 3)
(4, 2)
(3, 4)


In [13]:
f = tf.constant([[1.0, -2.0, -3.0], [-4.0, 5.0, -6.0]])
with tf.Session() as sess:
    print('f\n', sess.run(f))
    print('abs f\n', sess.run(tf.Tensor.__abs__(f)))
    print('or\n', sess.run(f.__abs__()))

f
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
abs f
 [[ 1.  2.  3.]
 [ 4.  5.  6.]]
or
 [[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [14]:
g = tf.Tensor.__abs__(f) + 0.5
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print('f add f:\n', sess.run(f.__add__(f)))
    print('f add f:\n', sess.run(tf.Tensor.__add__(f, f)))
    print('f add g:\n', sess.run(tf.Tensor.__add__(f, g)))
    print('f radd f:\n', sess.run(f.__radd__(f)))
    print('f radd f:\n', sess.run(tf.Tensor.__radd__(f, f)))
    print('f radd g:\n', sess.run(tf.Tensor.__radd__(f, g)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
f add f:
 [[  2.  -4.  -6.]
 [ -8.  10. -12.]]
f add f:
 [[  2.  -4.  -6.]
 [ -8.  10. -12.]]
f add g:
 [[  2.5   0.5   0.5]
 [  0.5  10.5   0.5]]
f radd f:
 [[  2.  -4.  -6.]
 [ -8.  10. -12.]]
f radd f:
 [[  2.  -4.  -6.]
 [ -8.  10. -12.]]
f radd g:
 [[  2.5   0.5   0.5]
 [  0.5  10.5   0.5]]


In [15]:
h = tf.cast(tf.constant([[0., -2.0, 0.], [-4.0, 0., 0.]]), tf.bool)
i = tf.cast(tf.Tensor.__add__(f, g), tf.bool)
with tf.Session() as sess:
    print('h:\n', sess.run(h))
    print('i:\n', sess.run(i))    
    print('h and h:\n', sess.run(h.__and__(h)))
    print('h and h:\n', sess.run(tf.Tensor.__and__(h, h)))
    print('h and i:\n', sess.run(tf.Tensor.__and__(h, i)))
    print('h radd h:\n', sess.run(h.__rand__(h)))
    print('h radd h:\n', sess.run(tf.Tensor.__rand__(h, h)))
    print('h radd i:\n', sess.run(tf.Tensor.__rand__(h, i)))

h:
 [[False  True False]
 [ True False False]]
i:
 [[ True  True  True]
 [ True  True  True]]
h and h:
 [[False  True False]
 [ True False False]]
h and h:
 [[False  True False]
 [ True False False]]
h and i:
 [[False  True False]
 [ True False False]]
h radd h:
 [[False  True False]
 [ True False False]]
h radd h:
 [[False  True False]
 [ True False False]]
h radd i:
 [[False  True False]
 [ True False False]]


In [16]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print('f div f:\n', sess.run(f.__div__(f)))
    print('f div f:\n', sess.run(tf.Tensor.__div__(f, f)))
    print('f div g:\n', sess.run(tf.Tensor.__div__(f, g)))
    print('f rdiv f:\n', sess.run(f.__rdiv__(f)))
    print('f rdiv f:\n', sess.run(tf.Tensor.__rdiv__(f, f)))
    print('f rdiv g:\n', sess.run(tf.Tensor.__rdiv__(f, g)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
f div f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f div f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f div g:
 [[ 0.66666669 -0.80000001 -0.85714287]
 [-0.8888889   0.90909094 -0.92307693]]
f rdiv f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f rdiv f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f rdiv g:
 [[ 1.5        -1.25       -1.16666663]
 [-1.125       1.10000002 -1.08333337]]


In [17]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print('f floordiv f:\n', sess.run(f.__floordiv__(f)))
    print('f floordiv f:\n', sess.run(tf.Tensor.__floordiv__(f, f)))
    print('f floordiv g:\n', sess.run(tf.Tensor.__floordiv__(f, g)))
    print('f rfloordiv f:\n', sess.run(f.__rfloordiv__(f)))
    print('f rfloordiv f:\n', sess.run(tf.Tensor.__rfloordiv__(f, f)))
    print('f rfloordiv g:\n', sess.run(tf.Tensor.__rfloordiv__(f, g)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
f floordiv f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f floordiv f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f floordiv g:
 [[ 0. -1. -1.]
 [-1.  0. -1.]]
f rfloordiv f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f rfloordiv f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f rfloordiv g:
 [[ 1. -2. -2.]
 [-2.  1. -2.]]


In [18]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print('f>=f:\n', sess.run(f.__ge__(f)))
    print('f>=f:\n', sess.run(tf.Tensor.__ge__(f, f)))
    print('f>=g:\n', sess.run(tf.Tensor.__ge__(f, g)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
f>=f:
 [[ True  True  True]
 [ True  True  True]]
f>=f:
 [[ True  True  True]
 [ True  True  True]]
f>=g:
 [[False False False]
 [False False False]]


In [19]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print(sess.run(tf.Tensor.__invert__(tf.Tensor.__ge__(f, g))))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
[[ True  True  True]
 [ True  True  True]]


In [20]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print('f<=f:\n', sess.run(f.__le__(f)))
    print('f<=f:\n', sess.run(f.__le__(f)))
    print('f<=g:\n', sess.run(tf.Tensor.__le__(f, g)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
f<=f:
 [[ True  True  True]
 [ True  True  True]]
f<=f:
 [[ True  True  True]
 [ True  True  True]]
f<=g:
 [[ True  True  True]
 [ True  True  True]]


In [21]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print('f<f:\n', sess.run(f.__lt__(f)))
    print('f<f:\n', sess.run(tf.Tensor.__lt__(f, f)))
    print('f<g:\n', sess.run(tf.Tensor.__lt__(f, g)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
f<f:
 [[False False False]
 [False False False]]
f<f:
 [[False False False]
 [False False False]]
f<g:
 [[ True  True  True]
 [ True  True  True]]


In [22]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print('f mod f:\n', sess.run(f.__mod__(f)))
    print('f mod f:\n', sess.run(tf.Tensor.__mod__(f, f)))
    print('f mod g:\n', sess.run(tf.Tensor.__mod__(f, g)))
    print('f rmod f:\n', sess.run(f.__rmod__(f)))
    print('f rmod f:\n', sess.run(tf.Tensor.__rmod__(f, f)))
    print('f rmod g:\n', sess.run(tf.Tensor.__rmod__(f, g)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
f mod f:
 [[ 0. -0. -0.]
 [-0.  0. -0.]]
f mod f:
 [[ 0. -0. -0.]
 [-0.  0. -0.]]
f mod g:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
f rmod f:
 [[ 0. -0. -0.]
 [-0.  0. -0.]]
f rmod f:
 [[ 0. -0. -0.]
 [-0.  0. -0.]]
f rmod g:
 [[ 0.5  0.5  0.5]
 [ 0.5  0.5  0.5]]


In [23]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print('f mul f:\n', sess.run(f.__mul__(f)))
    print('f mul f:\n', sess.run(tf.Tensor.__mul__(f, f)))
    print('f mul g:\n', sess.run(tf.Tensor.__mul__(f, g)))
    print('f rmul f:\n', sess.run(f.__rmul__(f)))
    print('f rmul f:\n', sess.run(tf.Tensor.__rmul__(f, f)))
    print('f rmul g:\n', sess.run(tf.Tensor.__rmul__(f, g)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
f mul f:
 [[  1.   4.   9.]
 [ 16.  25.  36.]]
f mul f:
 [[  1.   4.   9.]
 [ 16.  25.  36.]]
f mul g:
 [[  1.5  -5.  -10.5]
 [-18.   27.5 -39. ]]
f rmul f:
 [[  1.   4.   9.]
 [ 16.  25.  36.]]
f rmul f:
 [[  1.   4.   9.]
 [ 16.  25.  36.]]
f rmul g:
 [[  1.5  -5.  -10.5]
 [-18.   27.5 -39. ]]


In [24]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('neg f:\n', sess.run(f.__neg__()))
    print('neg f:\n', sess.run(tf.Tensor.__neg__(f)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
neg f:
 [[-1.  2.  3.]
 [ 4. -5.  6.]]
neg f:
 [[-1.  2.  3.]
 [ 4. -5.  6.]]


In [25]:
with tf.Session() as sess:
    print('h:\n', sess.run(h))
    print('i:\n', sess.run(i))    
    print('h or h:\n', sess.run(h.__or__(h)))
    print('h or h:\n', sess.run(tf.Tensor.__or__(h, h)))
    print('h or i:\n', sess.run(tf.Tensor.__or__(h, i)))
    print('h ror h:\n', sess.run(h.__ror__(h)))
    print('h ror h:\n', sess.run(tf.Tensor.__ror__(h, h)))
    print('h ror i:\n', sess.run(tf.Tensor.__ror__(h, i)))

h:
 [[False  True False]
 [ True False False]]
i:
 [[ True  True  True]
 [ True  True  True]]
h or h:
 [[False  True False]
 [ True False False]]
h or h:
 [[False  True False]
 [ True False False]]
h or i:
 [[ True  True  True]
 [ True  True  True]]
h ror h:
 [[False  True False]
 [ True False False]]
h ror h:
 [[False  True False]
 [ True False False]]
h ror i:
 [[ True  True  True]
 [ True  True  True]]


In [26]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print('f pow f:\n', sess.run(f.__pow__(f)))
    print('f pow f:\n', sess.run(tf.Tensor.__pow__(f, f)))
    print('f pow g:\n', sess.run(tf.Tensor.__pow__(f, g)))
    print('f rpow f:\n', sess.run(f.__rpow__(f)))
    print('f rpow f:\n', sess.run(tf.Tensor.__rpow__(f, f)))
    print('f rpow g:\n', sess.run(tf.Tensor.__rpow__(f, g)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
f pow f:
 [[  1.00000000e+00   2.50000000e-01  -3.70370373e-02]
 [  3.90625000e-03   3.12500000e+03   2.14334705e-05]]
f pow f:
 [[  1.00000000e+00   2.50000000e-01  -3.70370373e-02]
 [  3.90625000e-03   3.12500000e+03   2.14334705e-05]]
f pow g:
 [[  1.00000000e+00              nan              nan]
 [             nan   6.98771240e+03              nan]]
f rpow f:
 [[  1.00000000e+00   2.50000000e-01  -3.70370373e-02]
 [  3.90625000e-03   3.12500000e+03   2.14334705e-05]]
f rpow f:
 [[  1.00000000e+00   2.50000000e-01  -3.70370373e-02]
 [  3.90625000e-03   3.12500000e+03   2.14334705e-05]]
f rpow g:
 [[  1.50000000e+00   1.59999996e-01   2.33236160e-02]
 [  2.43865256e-03   5.03284375e+03   1.32592777e-05]]


In [27]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print('f sub f:\n', sess.run(f.__sub__(f)))
    print('f sub f:\n', sess.run(tf.Tensor.__sub__(f, f)))
    print('f sub g:\n', sess.run(tf.Tensor.__sub__(f, g)))
    print('f rsub f:\n', sess.run(f.__rsub__(f)))
    print('f rsub f:\n', sess.run(tf.Tensor.__rsub__(f, f)))
    print('f rsub g:\n', sess.run(tf.Tensor.__rsub__(f, g)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
f sub f:
 [[ 0.  0.  0.]
 [ 0.  0.  0.]]
f sub f:
 [[ 0.  0.  0.]
 [ 0.  0.  0.]]
f sub g:
 [[ -0.5  -4.5  -6.5]
 [ -8.5  -0.5 -12.5]]
f rsub f:
 [[ 0.  0.  0.]
 [ 0.  0.  0.]]
f rsub f:
 [[ 0.  0.  0.]
 [ 0.  0.  0.]]
f rsub g:
 [[  0.5   4.5   6.5]
 [  8.5   0.5  12.5]]


In [28]:
with tf.Session() as sess:
    print('f:\n', sess.run(f))
    print('g:\n', sess.run(g))
    print('f truediv f:\n', sess.run(f.__truediv__(f)))
    print('f truediv f:\n', sess.run(tf.Tensor.__truediv__(f, f)))
    print('f truediv g:\n', sess.run(tf.Tensor.__truediv__(f, g)))
    print('f rtruediv f:\n', sess.run(f.__rtruediv__(f)))
    print('f rtruediv f:\n', sess.run(tf.Tensor.__rtruediv__(f, f)))
    print('f rtruediv g:\n', sess.run(tf.Tensor.__rtruediv__(f, g)))

f:
 [[ 1. -2. -3.]
 [-4.  5. -6.]]
g:
 [[ 1.5  2.5  3.5]
 [ 4.5  5.5  6.5]]
f truediv f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f truediv f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f truediv g:
 [[ 0.66666669 -0.80000001 -0.85714287]
 [-0.8888889   0.90909094 -0.92307693]]
f rtruediv f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f rtruediv f:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
f rtruediv g:
 [[ 1.5        -1.25       -1.16666663]
 [-1.125       1.10000002 -1.08333337]]
